version: '3.1'

volumes:
    grafana-storage:

services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    env_file:
      - grafana.env
    restart: always
